version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db